---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-h2
        image: oscarfonts/h2
        ports:
        - containerPort: 1521
        - containerPort: 81
        env:
        - name: H2_OPTIONS
          value: -ifNotExists
        readinessProbe:
          tcpSocket:
            port: 1521
          initialDelaySeconds: 2
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  type: NodePort
  ports:
  - port: 1521
    name: "db"
  - port: 81
    nodePort: 30081
    name: "ui"
